Resources:
  TimestreamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: timestream.yaml
      Parameters:
        DatabaseName: "SensorDataDB"
        TableName: "SensorDataTable"

  IoTCoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iot-core.yaml
      Parameters:
        IoTRuleTopicName: "sdk/test/python"  # Topic name for IoT rules
        TimestreamDatabaseName: 
          Fn::ImportValue: "IotProjectDbName" 
        TimestreamTableName: 
          Fn::ImportValue: "IotProjectTableName"
     
  IoTEventsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iot-events.yaml
      Parameters:
        EmailAddress: "your-email@example.com"  # Replace with your email address
        DetectorModelName: "Q_BasicEventModel"
        TemperatureThreshold: 20.0
      
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml

  EC2GrafanaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2-grafana.yaml
      Parameters:
        PublicSubnetId: 
          Fn::ImportValue: "IOTEC2PublicSubnet1Id"
        ProjectSecurityGroup: 
          Fn::ImportValue: "IOTEC2SecurityGroupId"
      